addons:
  sonarqube: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.login=$SONAR_TOKEN -s settings.xml
cache:
  directories:
  - "$HOME/.m2/repository"