addons:
  sonarqube: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent -s settings.xml deploy sonar:sonar -Dsonar.login=$SONAR_TOKEN
cache:
  directories:
  - "$HOME/.m2/repository"