addons:
  sonarqube: true
language: java
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar -Dsonar.login=$SONAR_TOKEN -s settings.xml
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
    secure: aO0Q6/dfFQuWVc7nTFl6UOe9uFWmWTv9KTGK1DvDh99jKcw2QyG1srmHvutUUy3E7XWm6akauO7QZbthAyITNr6ZihKCUXEmG195O2K3JYgD2e/M0Kjko8oQaeJVZVoixY0HcKC/lnYsoN1SLF3x5mGtNKAtCe0lH7HEiK7EBzsdkEipHfSFrssgiQ3BjlVIY+O7Y+aHQL09shc0QFjpJ9tm+yK5nYfuiwM/L3iZ3o8j+KpK8bAasO/bZGzxg6J6+s4WmHX+67O+Rc2NLMe4SRrcBhrj7lyawJTHFjavB8FTvnHr35kPevYsh8CZrWQa0+TDsfOQK0Vlix4l00nybfIfcAjZ8l4X2dciuUSBsiGsYaVsFPUD8t8mqmUst859/L5wdmfu5W/GUttprpTmn9Khe/my4QV57no2Xg752OuEtzGrfMtJRuvx1LFknXn1fN6vrONlZzR/2xXksibiraqQa1LhRCuBqEbewVH8b39RZtc8Es6X50k4xSfZew5ha/E+TD3jaaNshnW/8vVsuLeUS/hZEwSa1w0qdK1mYOCFEFvtle9nkGg4PhexhsXbYXS6U0oGTXldGuVqVVTLVp8LkpKEQSmATbByI9bf9P3OnpksGxdJ8r8aY4NBYP28CA/IPHznSGUR5YCVWM2wM1n7gM0frNscBI0igNi+jf8=
    secure: xH4EhBSmJbYedzL8bSR+zbn1OBZvcF4dU3DkHIIIRQcQ7DIdKexI7snJ6dbkmzgVllUSmLQHBnE4pOu+eodvQ7iJhukBkAaPgs8X/MnMx3vw0hjAQEYtlx6WzVn7cuBfmFlK+4hoin0zh+sjEV2JbjbRsiPTZ9wY0DJQEsrYNnhAJNE9+uveyortFC01dme7vYs98Dv1tMz90gQTpwyp0lyTBwNW6lirb/+A0rvRX9yq2svoIkWClXuY0r7uYV6GEkXHarOoGI5X1h+1BAcHQYdq3DRD2T/DPjeLopAeMlgD5kaGa/9tRN1tccTOtrtYe+BpfpOtOwvb8c8kfhV31ALQg+fCze8Sb+uUQJbsCSmsfYSc85SPNQka799+zV5d4u6HGssKt4bMhcIf58Sd/6JaHq1YppQjl4m2/LaYwIuGsoio13lePGlpG3/Vjti/dU989hjcDT0+k2ACFeDQxru67GnSghhk63VRNbxKrRPvYOBR/QunPBQ6sOXaRG2J9qKcHofFYS4OsQOwPHPjrR6sApTpzD5K8H+UNhXf7BtwD8j+iMtHHthuGK/Cp25qDAFIIq8L6WEt7hSdqjDe3v4GbLPyutB9xmdXbqJaK03wLPIBolXKhrlNZCjUmuekleqQVdzN0acXbcWLO74WQaa2UVSWU8RmvkhbcyOLGdM=